import dayjs from 'dayjs/esm';

import { ICadastroAluno, NewCadastroAluno } from './cadastro-aluno.model';

export const sampleWithRequiredData: ICadastroAluno = {
  id: 10897,
  dataCadastro: dayjs('2024-12-23'),
  nome: 'hence',
  dn: dayjs('2024-12-24'),
  cep: 'sushi corr',
  endereco: 'next watery',
  fone: 'ugh',
  cpf: 'next at adumbr',
  filiacaoMae: 'unsteady',
  contatoEmergencia: 'embody reluctantly',
  foneEmergencia: 'lively overtrai',
  relacaoEmergencia: 'blossom writhing barring',
  autorizacao: true,
};

export const sampleWithPartialData: ICadastroAluno = {
  id: 5976,
  dataCadastro: dayjs('2024-12-23'),
  nome: 'throughout um down',
  dn: dayjs('2024-12-23'),
  cep: 'ick',
  endereco: 'buzzing',
  qd: 'sun partri',
  fone: 'slimy',
  certidao: 'usually abnormally',
  cartorio: 'ouch yuck',
  cpf: 'settler stack ',
  cras: 'legging affect commandeer',
  paiTelefone: 'cow',
  paiNaturalidade: 'off fairly towards',
  paiUf: 'wh',
  paiDataNascimento: dayjs('2024-12-23'),
  paiCpf: 'pish pack how',
  paiTituloEleitor: 'pressure what',
  paiZona: 'nippy as s',
  paiMunicipio: 'failing pants',
  filiacaoMae: 'failing wear zowie',
  maeTelefone: 'although charla',
  maeNaturalidade: 'discourse',
  maeTituloEleitor: 'duffel dimly linear',
  turno: 'MATUTINO',
  mediaEscolar: 30416.24,
  prioritario: 'SIM',
  obs: 'prime pacemaker',
  comportamentoEscola: 'AGITADO',
  adaptacoes: 'SIM',
  medicacao: 'NAO',
  medicacaoDesc: 'edge what ample',
  alergia: 'SIM',
  alergiaDesc: 'waist',
  historicoMedico: 'deep',
  pessoasTrabalham: 15412,
  tipoResidencia: 'OUTRO',
  tipoResidenciaDesc: 'aw version',
  situacaoResidencia: 'ALUGADA',
  contatoEmergencia: 'sizzling pfft',
  foneEmergencia: 'unlike',
  relacaoEmergencia: 'disconnection brave',
  autorizacao: false,
  fotoAluno: 'convalesce',
};

export const sampleWithFullData: ICadastroAluno = {
  id: 5074,
  dataCadastro: dayjs('2024-12-23'),
  matricula: 'rightfully',
  grupo: 'flood',
  nome: 'ah shear import',
  dn: dayjs('2024-12-23'),
  cep: 'and',
  endereco: 'drive sin following',
  qd: 'hungry whi',
  lote: 'awareness ',
  endnumero: 'lest',
  bairro: 'consequently',
  municipio: 'repeat',
  uf: 'sp',
  fone: 'outfox brightly',
  certidao: 'famously sometimes skyline',
  termo: 'tuxedo vibraphone miserly',
  cartorio: 'who community vivaciously',
  naturalidade: 'metabolite hence uh-huh',
  rg: 'but mathematics stea',
  cpf: 'provided',
  nis: 'lady',
  cras: 'pish',
  filiacaoPai: 'aw barracks whoever',
  paiTelefone: 'archive midst',
  paiNaturalidade: 'whole',
  paiUf: 'id',
  paiRg: 'offset',
  paiDataNascimento: dayjs('2024-12-24'),
  paiCpf: 'without fencin',
  paiNis: 'briefly yowza',
  paiTituloEleitor: 'meaningfully yuck',
  paiZona: 'pfft muddy',
  paiSecao: 'weight',
  paiMunicipio: 'sans if',
  filiacaoMae: 'lava save',
  maeTelefone: 'silt against',
  maeNaturalidade: 'adjudge yet',
  maeUf: 'tr',
  maeRg: 'ack unbalance given',
  maeDataNascimento: dayjs('2024-12-24'),
  maeCpf: 'coil',
  maeNis: 'oh',
  maeTituloEleitor: 'govern',
  maeZona: 'save defic',
  maeSecao: 'whose',
  maeMunicipio: 'loudly recompense',
  nomeEscola: 'acidic furthermore whereas',
  anoCursando: 'pro finally than',
  turno: 'NOTURNO',
  mediaEscolar: 8312.8,
  prioritario: 'SIM',
  obs: 'boohoo',
  comportamentoCasa: 'TRANQUILO',
  comportamentoEscola: 'AGITADO',
  deficiencia: 'SIM',
  adaptacoes: 'SIM',
  medicacao: 'SIM',
  medicacaoDesc: 'athwart practical wallop',
  alergia: 'NAO',
  alergiaDesc: 'appertain gosh',
  historicoMedico: 'daintily',
  rendaFamiliar: 'than',
  pessoasTrabalham: 28734,
  numPessoasLar: 12715,
  beneficioSocial: 'SIM',
  beneficios: 'that finally',
  tipoResidencia: 'APARTAMENTO',
  tipoResidenciaDesc: 'repeatedly',
  situacaoResidencia: 'ALUGADA',
  situacaoResidenciaDesc: 'taxicab circulate solder',
  contatoEmergencia: 'following assured',
  foneEmergencia: 'taxicab loaf',
  relacaoEmergencia: 'unnecessarily',
  autorizacao: true,
  fotoAluno: 'until fortunately alliance',
  fotoMae: 'maroon huzzah spectacles',
};

export const sampleWithNewData: NewCadastroAluno = {
  dataCadastro: dayjs('2024-12-24'),
  nome: 'athwart lovely',
  dn: dayjs('2024-12-23'),
  cep: 'march tigh',
  endereco: 'enlightened yearningly fully',
  fone: 'brush',
  cpf: 'claw',
  filiacaoMae: 'tankful',
  contatoEmergencia: 'once omelet',
  foneEmergencia: 'despite mobilis',
  relacaoEmergencia: 'poetry',
  autorizacao: false,
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
